
color_items = {}

color_items["indigo"] = 1
color_items["gold"] = 1
color_items["chartreuse green"] = 1
color_items["firebrick"] = 1
color_items["indianred"] = 1
color_items["yellow"] = 1
color_items["cobalt"] = 1
color_items["darkolivegreen"] = 1
color_items["darkseagreen"] = 1
color_items["slate gray"] = 1
color_items["mediumvioletred"] = 1
color_items["mediumorchid"] = 1
color_items["silver"] = 1
color_items["papayawhip"] = 1
color_items["mediumslateblue"] = 1
color_items["black"] = 1
color_items["cerise"] = 1
color_items["carmine"] = 1
color_items["lightsalmon"] = 1
color_items["brown"] = 1
color_items["coffee"] = 1
color_items["lightseagreen"] = 1
color_items["lightcyan"] = 1
color_items["darkorchid"] = 1
color_items["dimgray"] = 1
color_items["lawngreen"] = 1
color_items["cyan"] = 1
color_items["auburn"] = 1
color_items["orange red"] = 1
color_items["skyblue"] = 1
color_items["gray"] = 1
color_items["darkturquoise"] = 1
color_items["goldenrod"] = 1
color_items["darkgreen"] = 1
color_items["darkviolet"] = 1
color_items["midnightblue"] = 1
color_items["lightpink"] = 1
color_items["teal"] = 1
color_items["darkgray"] = 1
color_items["darkmagenta"] = 1
color_items["spring bud"] = 1
color_items["lilac"] = 1
color_items["baby blue"] = 1
color_items["jade"] = 1
color_items["yellowgreen"] = 1
color_items["thistle"] = 1
color_items["llightgray"] = 1
color_items["navy"] = 1
color_items["darkblue"] = 1
color_items["orchid"] = 1
color_items["blue"] = 1
color_items["ghostwhite"] = 1
color_items["honeydew"] = 1
color_items["cornflowerblue"] = 1
color_items["purple"] = 1
color_items["darkkhaki"] = 1
color_items["burgundy"] = 1
color_items["champagne"] = 1
color_items["cornsilk"] = 1
color_items["red"] = 1
color_items["bisque"] = 1
color_items["darkcyan"] = 1
color_items["khaki"] = 1
color_items["deepskyblue"] = 1
color_items["byzantium"] = 1
color_items["magenta rose"] = 1
color_items["wheat color"] = 1
color_items["steelblue"] = 1
color_items["darkred"] = 1
color_items["gainsboro"] = 1
color_items["bronze"] = 1
color_items["mediumturquoise"] = 1
color_items["floralwhite"] = 1
color_items["aqua"] = 1
color_items["mistyrose"] = 1
color_items["darksalmon"] = 1
color_items["beige"] = 1
color_items["azure"] = 1
color_items["blush"] = 1
color_items["aliceblue"] = 1
color_items["amber"] = 1
color_items["copper"] = 1
color_items["puce"] = 1
color_items["greenyellow"] = 1
color_items["fuchsia"] = 1
color_items["olivedrab"] = 1
color_items["sienna"] = 1
color_items["mediumpurple"] = 1
color_items["lightcoral"] = 1
color_items["navajowhite"] = 1
color_items["blue violet"] = 1
color_items["palegreen"] = 1
color_items["harlequin"] = 1
color_items["burlywood"] = 1
color_items["seashell"] = 1
color_items["mediumspringgreen"] = 1
color_items["royalblue"] = 1
color_items["chartreuse"] = 1
color_items["blanchedalmond"] = 1
color_items["peru"] = 1
color_items["mauve"] = 1
color_items["aquamarine"] = 1
color_items["white"] = 1
color_items["lightgoldenrodyellow"] = 1
color_items["darkslategray"] = 1
color_items["ivory"] = 1
color_items["dodgerblue"] = 1
color_items["navy blue"] = 1
color_items["lemonchiffon"] = 1
color_items["chocolate"] = 1
color_items["crimson"] = 1
color_items["jungle green"] = 1
color_items["forestgreen"] = 1
color_items["slateblue"] = 1
color_items["mintcream"] = 1
color_items["prussian blue"] = 1
color_items["antiquewhite"] = 1
color_items["electric blue"] = 1
color_items["hotpink"] = 1
color_items["moccasin"] = 1
color_items["desert sand"] = 1
color_items["limegreen"] = 1
color_items["saddlebrown"] = 1
color_items["darkslateblue"] = 1
color_items["lightskyblue"] = 1
color_items["deeppink"] = 1
color_items["cerulean"] = 1
color_items["taupe"] = 1
color_items["darkgoldenrod"] = 1
color_items["turquoise"] = 1
color_items["maroon"] = 1
color_items["erin"] = 1
color_items["scarlet"] = 1
color_items["sandybrown"] = 1
color_items["spring green"] = 1
color_items["tan"] = 1
color_items["magenta"] = 1
color_items["rosybrown"] = 1
color_items["pink"] = 1
color_items["lightblue"] = 1
color_items["palevioletred"] = 1
color_items["mediumseagreen"] = 1
color_items["darkorange"] = 1
color_items["powderblue"] = 1
color_items["seagreen"] = 1
color_items["snow"] = 1
color_items["blue green"] = 1
color_items["mediumblue"] = 1
color_items["green"] = 1
color_items["viridian"] = 1
color_items["paleturquoise"] = 1
color_items["palegoldenrod"] = 1
color_items["whitesmoke"] = 1
color_items["orange color"] = 1
color_items["salmon"] = 1
color_items["lightslategray"] = 1
color_items["oldlace"] = 1
color_items["lightgreen"] = 1
color_items["lightsteelblue"] = 1
color_items["cadetblue"] = 1
color_items["lightyellow"] = 1
color_items["lavenderblush"] = 1
color_items["linen"] = 1
color_items["mediumaquamarine"] = 1
color_items["persian blue"] = 1
color_items["peachpuff"] = 1
color_items["red violet"] = 1