
elec_items = {}

elec_items["camcorder"] = 1
elec_items["camera"] = 1
elec_items["car stuff"] = 1
elec_items["gadget"] = 1
elec_items["corporate gadget"] = 1
elec_items["dvd player"] = 1
elec_items["game machine"] = 1
elec_items["home appliance"] = 1
elec_items["ipods"] = 1
elec_items["laptop"] = 1
elec_items["tv"] = 1
elec_items["lcd tv"] = 1
elec_items["plasma tv"] = 1
elec_items["mobile phone"] = 1
elec_items["mp3 player"] = 1
elec_items["software"] = 1
elec_items["speaker"] = 1
elec_items["spy gadget"] = 1
elec_items["watch"] = 1
elec_items["watches"] = 1
elec_items["laptop"] = 1
elec_items["nintendo"] = 1
elec_items["ps3"] = 1
elec_items["xbox"] = 1
elec_items["wii"] = 1
elec_items["notebook"] = 1
elec_items["tablet"] = 1
elec_items["phablet"] = 1
elec_items["desktop"] = 1
elec_items["computer"] = 1
elec_items["television"] = 1
elec_items["camcoder"] = 1
elec_items["camera"] = 1
elec_items["smart watch"] = 1
elec_items["battery"] = 1
elec_items["batteries"] = 1
elec_items["chargers"] = 1
elec_items["bluetooth headset"] = 1
elec_items["cables"] = 1
elec_items["car speakers"] = 1
elec_items["cartridge"] = 1
elec_items["clock radio"] = 1
elec_items["corded phone"] = 1
elec_items["cordless keyboard and mice"] = 1
elec_items["cordless phone"] = 1
elec_items["data cards"] = 1
elec_items["digital camera"] = 1
elec_items["digital photo frame"] = 1
elec_items["digital slr camera"] = 1
elec_items["gaming"] = 1
elec_items["handsfree"] = 1
elec_items["hard disk"] = 1
elec_items["headset"] = 1
elec_items["ipad"] = 1
elec_items["ipod and psp peripheral"] = 1
elec_items["laptop adaptor"] = 1
elec_items["laptop bags"] = 1
elec_items["laptop battery"] = 1
elec_items["laptop keyboard"] = 1
elec_items["laptop memory kit"] = 1
elec_items["laptop mouse"] = 1
elec_items["laptop peripheral"] = 1
elec_items["laptop peripheral"] = 1
elec_items["laptop skin"] = 1
elec_items["mac game"] = 1
elec_items["memory card"] = 1
elec_items["memory card"] = 1
elec_items["microphone"] = 1
elec_items["mobile adaptor"] = 1
elec_items["mobile battery"] = 1
elec_items["mobile charger"] = 1
elec_items["mobile phone pouch"] = 1
elec_items["mobile skin"] = 1
elec_items["mouse pad"] = 1
elec_items["networking"] = 1
elec_items["nintendo 3ds game"] = 1
elec_items["nintendo game"] = 1
elec_items["nintendo nd"] = 1
elec_items["pc game"] = 1
elec_items["pen drive"] = 1
elec_items["ps vita game"] = 1
elec_items["ps2 game"] = 1
elec_items["ps3 game"] = 1
elec_items["psp game"] = 1
elec_items["router"] = 1
elec_items["screen protector"] = 1
elec_items["speakers"] = 1
elec_items["speakers"] = 1
elec_items["surge protector"] = 1
elec_items["tv accessories"] = 1
elec_items["usb devices"] = 1
elec_items["webcams"] = 1
elec_items["wii u game"] = 1
elec_items["adapter"] = 1
elec_items["usb"] = 1
elec_items["wireless"] = 1
elec_items["wireless usb adapter"] = 1
elec_items["xbox game"] = 1