

kitchen_items = {}
kitchen_items["nut-cracker"] = 1kitchen_items["non-stick pan"] = 1kitchen_items["nef"] = 1kitchen_items["palayok"] = 1kitchen_items["pastry brush"] = 1kitchen_items["pie bird"] = 1kitchen_items["picnic basket"] = 1kitchen_items["pestle and mortar"] = 1kitchen_items["napkin ring"] = 1kitchen_items["napkin holder"] = 1kitchen_items["measuring cup"] = 1kitchen_items["makitra"] = 1kitchen_items["lazy susan"] = 1kitchen_items["kettle"] = 1kitchen_items["meat thermometer"] = 1kitchen_items["bain-marie"] = 1kitchen_items["napkin"] = 1kitchen_items["muffin tin"] = 1kitchen_items["mop"] = 1kitchen_items["pizza stone"] = 1kitchen_items["placemat"] = 1kitchen_items["tablecloth"] = 1kitchen_items["table setting"] = 1kitchen_items["sujeo"] = 1kitchen_items["stainless steel soap"] = 1kitchen_items["terrine"] = 1kitchen_items["toast rack"] = 1kitchen_items["tureen"] = 1kitchen_items["trencher"] = 1kitchen_items["tray"] = 1kitchen_items["soap dispenser"] = 1kitchen_items["item of silverware"] = 1kitchen_items["rice cooker"] = 1kitchen_items["potjie"] = 1kitchen_items["porringer"] = 1kitchen_items["platter"] = 1kitchen_items["rolling pin"] = 1kitchen_items["salt cellar"] = 1kitchen_items["sheet pan"] = 1kitchen_items["sauce boat"] = 1kitchen_items["salver"] = 1kitchen_items["juicer"] = 1kitchen_items["melamine resin"] = 1kitchen_items["charger"] = 1kitchen_items["dish"] = 1kitchen_items["doily"] = 1kitchen_items["cauldron"] = 1kitchen_items["double boiler"] = 1kitchen_items["bread pan"] = 1kitchen_items["cruet"] = 1kitchen_items["crock"] = 1kitchen_items["cherry pitter"] = 1kitchen_items["chip pan"] = 1kitchen_items["butter dish"] = 1kitchen_items["burr mill"] = 1kitchen_items["casserole"] = 1kitchen_items["bundt cake"] = 1kitchen_items["biscuit joiner"] = 1kitchen_items["dutch oven"] = 1kitchen_items["cast-iron cookware"] = 1kitchen_items["griddle"] = 1kitchen_items["item of dishware"] = 1kitchen_items["jamonera"] = 1kitchen_items["cezve"] = 1kitchen_items["grande baroque"] = 1kitchen_items["garbage disposal"] = 1kitchen_items["billycan"] = 1kitchen_items["egg cup"] = 1kitchen_items["can opener"] = 1kitchen_items["egg timer"] = 1kitchen_items["chafing-dish"] = 1kitchen_items["french butter dish"] = 1kitchen_items["set of kitchen scales"] = 1kitchen_items["timbale"] = 1kitchen_items["vegetable brush"] = 1kitchen_items["zarf"] = 1kitchen_items["turkey frills"] = 1kitchen_items["bedourie oven"] = 1kitchen_items["brustolina"] = 1kitchen_items["bridge spouted vessel"] = 1kitchen_items["spoon rest"] = 1kitchen_items["biscuit tin"] = 1kitchen_items["doufeu"] = 1kitchen_items["pair of kitchen shears"] = 1kitchen_items["pair of kitchen tongs"] = 1kitchen_items["nef"] = 1kitchen_items["francis 1st"] = 1kitchen_items["kitchen knife"] = 1kitchen_items["japanese kitchen utensil"] = 1kitchen_items["ice cube tray"] = 1kitchen_items["pan dan"] = 1kitchen_items["crepulja"] = 1kitchen_items["pot boiler"] = 1kitchen_items["ramekin"] = 1
kitchen_items["sac"] = 1kitchen_items["juice squeezer"] = 1kitchen_items["plated ware"] = 1kitchen_items["creamer"] = 1kitchen_items["cookware"] = 1kitchen_items["centrepiece"] = 1
kitchen_items["apple corer"] = 1
kitchen_items["apple cutter"] = 1
kitchen_items["baster"] = 1
kitchen_items["biscuit cutter"] = 1
kitchen_items["biscuit press"] = 1
kitchen_items["blow torch"] = 1
kitchen_items["boil over preventer"] = 1
kitchen_items["bottle opener"] = 1
kitchen_items["bowl"] = 1
kitchen_items["bread knife"] = 1
kitchen_items["browning tray"] = 1
kitchen_items["butter curler"] = 1
kitchen_items["cake and pie server"] = 1
kitchen_items["cheese knife"] = 1
kitchen_items["cheesecloth"] = 1
kitchen_items["chef's knife"] = 1
kitchen_items["cherry pitter"] = 1
kitchen_items["chinoise"] = 1
kitchen_items["colander"] = 1
kitchen_items["corkscrew"] = 1
kitchen_items["crab cracker"] = 1
kitchen_items["cutting board"] = 1
kitchen_items["dough scraper"] = 1
kitchen_items["egg piercer"] = 1
kitchen_items["egg poacher"] = 1
kitchen_items["egg separator"] = 1
kitchen_items["egg slicer"] = 1
kitchen_items["egg timer"] = 1
kitchen_items["fillet knife"] = 1
kitchen_items["fish scaler"] = 1
kitchen_items["fish slice"] = 1
kitchen_items["flour sifter"] = 1
kitchen_items["food mill"] = 1
kitchen_items["funnel"] = 1
kitchen_items["garlic press"] = 1
kitchen_items["grapefruit knife"] = 1
kitchen_items["grater"] = 1
kitchen_items["gravy strainer"] = 1
kitchen_items["herb chopper"] = 1
kitchen_items["ladle"] = 1
kitchen_items["lame"] = 1
kitchen_items["lemon reamer"] = 1
kitchen_items["lemon squeezer"] = 1
kitchen_items["lobster pick"] = 1
kitchen_items["mandoline"] = 1
kitchen_items["mated colander pot"] = 1
kitchen_items["measuring jug"] = 1
kitchen_items["measuring spoon"] = 1
kitchen_items["meat grinder"] = 1
kitchen_items["meat tenderiser"] = 1
kitchen_items["meat thermometer"] = 1
kitchen_items["melon baller"] = 1
kitchen_items["mezzaluna"] = 1
kitchen_items["mortar and pestle"] = 1
kitchen_items["nutcracker"] = 1
kitchen_items["nutmeg grater"] = 1
kitchen_items["oven glove"] = 1
kitchen_items["pastry bag"] = 1
kitchen_items["pastry blender"] = 1
kitchen_items["pastry brush"] = 1
kitchen_items["pastry wheel"] = 1
kitchen_items["peel"] = 1
kitchen_items["peeler"] = 1
kitchen_items["pepper mill"] = 1
kitchen_items["pie bird"] = 1
kitchen_items["pizza cutter"] = 1
kitchen_items["potato masher"] = 1
kitchen_items["potato ricer"] = 1
kitchen_items["pot-holder"] = 1
kitchen_items["poultry shears"] = 1
kitchen_items["ricer"] = 1
kitchen_items["roller docker"] = 1
kitchen_items["rolling pin"] = 1
kitchen_items["salt shaker"] = 1
kitchen_items["scales"] = 1
kitchen_items["scissors"] = 1
kitchen_items["scoop"] = 1
kitchen_items["shellfish scraper"] = 1
kitchen_items["sieve"] = 1
kitchen_items["slotted spoon"] = 1
kitchen_items["spatula"] = 1
kitchen_items["spider"] = 1
kitchen_items["sugar thermometer"] = 1
kitchen_items["tamis"] = 1
kitchen_items["tin opener"] = 1
kitchen_items["tomato knife"] = 1
kitchen_items["tongs"] = 1
kitchen_items["trussing needle"] = 1
kitchen_items["whisk"] = 1
kitchen_items["wooden spoon"] = 1
kitchen_items["zester"] = 1

kitchen_items["biscuit mould"] = 1
kitchen_items["cookie cutter"] = 1
kitchen_items["cookie mould"] = 1
kitchen_items["cookie press"] = 1
kitchen_items["blowtorch"] = 1
kitchen_items["blowlamp"] = 1
kitchen_items["milk watcher"] = 1
kitchen_items["milk guard"] = 1
kitchen_items["pot minder"] = 1
kitchen_items["browning plate"] = 1
kitchen_items["browning bowl"] = 1
kitchen_items["cake shovel"] = 1
kitchen_items["pie cutter"] = 1
kitchen_items["olive stoner"] = 1
kitchen_items["chinois"] = 1
kitchen_items["lobster cracker"] = 1
kitchen_items["cutting board"] = 1
kitchen_items["bench scraper"] = 1
kitchen_items["scraper"] = 1
kitchen_items["urokotori"] = 1
kitchen_items["spatula"] = 1
kitchen_items["turner"] = 1
kitchen_items["cheese grater"] = 1
kitchen_items["shredder"] = 1
kitchen_items["gravy separator"] = 1
kitchen_items["lobster fork"] = 1
kitchen_items["measuring cup"] = 1
kitchen_items["measuring jar"] = 1
kitchen_items["mincer"] = 1
kitchen_items["molcajete"] = 1
kitchen_items["oven mitt"] = 1
kitchen_items["basting brush"] = 1
kitchen_items["pizza shovel"] = 1
kitchen_items["potato peeler"] = 1
kitchen_items["burr mill"] = 1
kitchen_items["burr grinder"] = 1
kitchen_items["pepper grinder"] = 1
kitchen_items["pie vent"] = 1
kitchen_items["pie funnel"] = 1
kitchen_items["pizza slicer"] = 1
kitchen_items["kitchen scales"] = 1
kitchen_items["weighing scales"] = 1
kitchen_items["kitchen scissors"] = 1
kitchen_items["ice cream scoop"] = 1
kitchen_items["sifter"] = 1
kitchen_items["strainer"] = 1
kitchen_items["skimmer"] = 1
kitchen_items["sieves"] = 1
kitchen_items["spoon sieves"] = 1
kitchen_items["spoon skimmers"] = 1
kitchen_items["or basket skimmers"] = 1
kitchen_items["candy thermometer"] = 1
kitchen_items["drum sieve"] = 1
kitchen_items["can opener"] = 1
kitchen_items["balloon whisk"] = 1
kitchen_items["gravy whisk"] = 1
kitchen_items["flat whisk"] = 1
kitchen_items["flat coil whisk"] = 1
kitchen_items["bell whisk"] = 1
kitchen_items["sugar bowl"] = 1
kitchen_items["roaster"] = 1
kitchen_items["kettle"] = 1
kitchen_items["corksrew"] = 1
kitchen_items["potholder"] = 1
kitchen_items["ricer"] = 1
kitchen_items["pie plate"] = 1
kitchen_items["silverware"] = 1
kitchen_items["ice pick"] = 1
kitchen_items["nesting bowls"] = 1
kitchen_items["griddle"] = 1
kitchen_items["basting brush"] = 1
kitchen_items["pepper shaker"] = 1
kitchen_items["oven"] = 1
kitchen_items["dish"] = 1
kitchen_items["vegetable brush"] = 1
kitchen_items["placemat"] = 1
kitchen_items["blender"] = 1
kitchen_items["vegetable peeler"] = 1
kitchen_items["oven glove"] = 1
kitchen_items["whisk broom"] = 1
kitchen_items["mixing bowl"] = 1
kitchen_items["cup"] = 1
kitchen_items["mandolin"] = 1
kitchen_items["butter dish"] = 1
kitchen_items["broom"] = 1
kitchen_items["dish soap"] = 1
kitchen_items["mug"] = 1
kitchen_items["teapot"] = 1
kitchen_items["raclette grill"] = 1
kitchen_items["creamer"] = 1
kitchen_items["cupcake pan"] = 1
kitchen_items["potato masher"] = 1
kitchen_items["serving pieces"] = 1
kitchen_items["stove"] = 1
kitchen_items["apron"] = 1
kitchen_items["steel wool"] = 1
kitchen_items["rice cooker"] = 1
kitchen_items["ice cube tray"] = 1
kitchen_items["food processor"] = 1
kitchen_items["ladle"] = 1
kitchen_items["spice rack"] = 1
kitchen_items["mop"] = 1
kitchen_items["garbage compactor"] = 1
kitchen_items["fridge"] = 1
kitchen_items["popcorn popper"] = 1
kitchen_items["plastic bags"] = 1
kitchen_items["spoon"] = 1
kitchen_items["pastry bag"] = 1
kitchen_items["batter"] = 1
kitchen_items["slow cooker"] = 1
kitchen_items["fryer"] = 1
kitchen_items["whisk"] = 1
kitchen_items["coffee maker"] = 1
kitchen_items["broiler"] = 1
kitchen_items["dutch oven"] = 1
kitchen_items["sauce pan"] = 1
kitchen_items["coffee pot"] = 1
kitchen_items["garbage bag"] = 1
kitchen_items["steamer"] = 1
kitchen_items["egg poacher"] = 1
kitchen_items["pizza cutter"] = 1
kitchen_items["tureen"] = 1
kitchen_items["whip"] = 1
kitchen_items["cake slice"] = 1
kitchen_items["skewer"] = 1
kitchen_items["dish towel"] = 1
kitchen_items["tray"] = 1
kitchen_items["trash can"] = 1
kitchen_items["poultry shears"] = 1
kitchen_items["vegetable bin"] = 1
kitchen_items["microwave oven"] = 1
kitchen_items["garlic press"] = 1
kitchen_items["mincer"] = 1
kitchen_items["bread knife"] = 1
kitchen_items["extractor hood"] = 1
kitchen_items["sponge"] = 1
kitchen_items["baster"] = 1
kitchen_items["bundt pan"] = 1
kitchen_items["casserole pan"] = 1
kitchen_items["trivet"] = 1
kitchen_items["gelatine mold"] = 1
kitchen_items["fondue pot"] = 1
kitchen_items["saucer"] = 1
kitchen_items["spice jar"] = 1
kitchen_items["grill pan"] = 1
kitchen_items["knife sharpener"] = 1
kitchen_items["steak knife"] = 1
kitchen_items["marinate"] = 1
kitchen_items["nut cracker"] = 1
kitchen_items["cleanser"] = 1
kitchen_items["egg beater"] = 1
kitchen_items["opener"] = 1
kitchen_items["wok"] = 1
kitchen_items["beater"] = 1
kitchen_items["bread basket"] = 1
kitchen_items["reamer"] = 1
kitchen_items["knife"] = 1
kitchen_items["butcher block"] = 1
kitchen_items["dish rack"] = 1
kitchen_items["soup bowl"] = 1
kitchen_items["honey dipper"] = 1
kitchen_items["cutting board"] = 1
kitchen_items["toaster oven"] = 1
kitchen_items["quiche pan"] = 1
kitchen_items["hamburger press"] = 1
kitchen_items["spatula"] = 1
kitchen_items["baking dish"] = 1
kitchen_items["flatware"] = 1
kitchen_items["water filter"] = 1
kitchen_items["strainer"] = 1
kitchen_items["sieve"] = 1
kitchen_items["table"] = 1
kitchen_items["peeler"] = 1
kitchen_items["ramekin"] = 1
kitchen_items["crockpot"] = 1
kitchen_items["dishwasher"] = 1
kitchen_items["plastic wrap"] = 1
kitchen_items["shelves"] = 1
kitchen_items["mixer"] = 1
kitchen_items["platter"] = 1
kitchen_items["pie pan"] = 1
kitchen_items["range"] = 1
kitchen_items["serving platter"] = 1
kitchen_items["roasting pan"] = 1
kitchen_items["spices"] = 1
kitchen_items["sink"] = 1
kitchen_items["tea cup"] = 1
kitchen_items["tea infuser"] = 1
kitchen_items["shears"] = 1
kitchen_items["sugar sifter"] = 1
kitchen_items["slicer"] = 1
kitchen_items["sifter"] = 1
kitchen_items["muffin pan"] = 1
kitchen_items["jar"] = 1
kitchen_items["pot"] = 1
kitchen_items["convection oven"] = 1
kitchen_items["coffee machine"] = 1
kitchen_items["rolling pin"] = 1
kitchen_items["carafe"] = 1
kitchen_items["scissors"] = 1
kitchen_items["skillet"] = 1
kitchen_items["tablecloth"] = 1
kitchen_items["grater"] = 1
kitchen_items["waffle iron"] = 1
kitchen_items["percolator"] = 1
kitchen_items["bottle opener"] = 1
kitchen_items["pepper mill"] = 1
kitchen_items["bun warmer"] = 1
kitchen_items["meat fork"] = 1
kitchen_items["waste basket"] = 1
kitchen_items["can opener"] = 1
kitchen_items["nut pick"] = 1
kitchen_items["salad spinner"] = 1
kitchen_items["kitchen scales"] = 1
kitchen_items["hand mixer"] = 1
kitchen_items["steak hammer"] = 1
kitchen_items["oven mitt"] = 1
kitchen_items["fork"] = 1
kitchen_items["ice box"] = 1
kitchen_items["funnel"] = 1
kitchen_items["jug"] = 1
kitchen_items["yogurt maker"] = 1
kitchen_items["pitcher"] = 1
kitchen_items["paper towels"] = 1
kitchen_items["cabinet"] = 1
kitchen_items["stockpot"] = 1
kitchen_items["meat tenderizer"] = 1
kitchen_items["pepper grinder"] = 1
kitchen_items["garbage can"] = 1
kitchen_items["fondue set"] = 1
kitchen_items["parchment paper"] = 1
kitchen_items["casserole"] = 1
kitchen_items["grill"] = 1
kitchen_items["juice glass"] = 1
kitchen_items["hot plate"] = 1
kitchen_items["cheese cloth"] = 1
kitchen_items["paring knife"] = 1
kitchen_items["coffee grinder"] = 1
kitchen_items["waxed paper"] = 1
kitchen_items["ice bucket"] = 1
kitchen_items["colander"] = 1
kitchen_items["baking pan"] = 1
kitchen_items["egg-cup"] = 1
kitchen_items["charcoal grill"] = 1
kitchen_items["pressure cooker"] = 1
kitchen_items["baking sheet"] = 1
kitchen_items["champagne cooler"] = 1
kitchen_items["honey pot"] = 1
kitchen_items["cookie press"] = 1
kitchen_items["cookie cutter"] = 1
kitchen_items["salad bowl"] = 1
kitchen_items["chest freezer"] = 1
kitchen_items["meat thermometer"] = 1
kitchen_items["teaspoon"] = 1
kitchen_items["timer"] = 1
kitchen_items["decanter"] = 1
kitchen_items["custard cup"] = 1
kitchen_items["tart pan"] = 1
kitchen_items["mold"] = 1
kitchen_items["wine shelf"] = 1
kitchen_items["flour sifter"] = 1
kitchen_items["lid"] = 1
kitchen_items["tongs"] = 1
kitchen_items["grinder"] = 1
kitchen_items["coffee mill"] = 1
kitchen_items["teakettle"] = 1
kitchen_items["toaster"] = 1
kitchen_items["bowl"] = 1
kitchen_items["freezer"] = 1
kitchen_items["lasagne pan"] = 1
kitchen_items["jar opener"] = 1
kitchen_items["poacher"] = 1
kitchen_items["deep fryer"] = 1
kitchen_items["cake stand"] = 1
kitchen_items["tumbler"] = 1
kitchen_items["thermometer"] = 1
kitchen_items["frying pan"] = 1
kitchen_items["crepe pan"] = 1
kitchen_items["fruit bowl"] = 1
kitchen_items["soap"] = 1
kitchen_items["pan"] = 1
kitchen_items["barbecue grill"] = 1
kitchen_items["ice cream maker"] = 1
kitchen_items["pizza wheel"] = 1
kitchen_items["springform pan"] = 1
kitchen_items["cupboard"] = 1
kitchen_items["gravy boat"] = 1
kitchen_items["plate"] = 1
kitchen_items["sauce boat"] = 1
kitchen_items["juicer"] = 1
kitchen_items["tablespoon"] = 1
kitchen_items["iron skillet"] = 1
kitchen_items["infuser"] = 1
kitchen_items["basket"] = 1
kitchen_items["sharpening steel"] = 1
kitchen_items["pestle"] = 1
kitchen_items["masher"] = 1
kitchen_items["meat grinder"] = 1
kitchen_items["spring-clip tin"] = 1
kitchen_items["egg timer"] = 1
kitchen_items["refrigerator"] = 1
kitchen_items["stew pot"] = 1
kitchen_items["trash bags"] = 1
kitchen_items["icing spatula"] = 1
kitchen_items["pizza stone"] = 1
kitchen_items["cooker"] = 1
kitchen_items["cake pan"] = 1
kitchen_items["pizza pan"] = 1
kitchen_items["counter"] = 1
kitchen_items["cutlery"] = 1
kitchen_items["souffle dish"] = 1
kitchen_items["napkin"] = 1
kitchen_items["salt shaker"] = 1
kitchen_items["scoop"] = 1
kitchen_items["garbage disposal"] = 1
kitchen_items["cookie sheet"] = 1
kitchen_items["measuring cup"] = 1
kitchen_items["chopsticks"] = 1
kitchen_items["bottle"] = 1
kitchen_items["tin"] = 1
kitchen_items["corer"] = 1
kitchen_items["measuring spoon"] = 1
kitchen_items["cookbook"] = 1
kitchen_items["corn pick"] = 1
kitchen_items["cast iron pan"] = 1